blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/T4Tier3/Authentication-mircoservices/discussions
    about: Ask usage questions or propose ideas before filing an issue.
